export const workExperienceData = [
  {
    id: 1,
    title: "Software Development Engineer",
    company: "Picton Mahoney Asset Management",
    duration: "September 2023 - Present",
    location: "Toronto, ON",
    responsibilities: [
      `Next.js Expertise: Developed and maintained a scalable front-end application using Next.js and React.js,
leveraging its server-side rendering (SSR) and static site generation (SSG) capabilities for optimal
performance and SEO.`,
      `Secured financial reporting interfaces using OAuth 2.0 and JWT with robust token handling, validation, refresh logic, and role-based access in a multi-tenant setup`,
      `Integrated OpenAI APIs into enterprise Node.js applications using TypeScript, implementing AI-powered features for financial analysis and portfolio management with robust error handling and response validation`,
      `Implemented API testing with Postman and Swagger UI, ensuring seamless integration of React/Next.js frontend with backend REST services and validating complex financial data.`,
      `Integrated RESTful APIs using Axios for secure and efficient front-end/back-end communication.`,
      `Built interactive data visualizations with Plotly.js to enable effective analysis of complex datasets.`,
      `Built enterprise-grade REST APIs using Node.js and NestJS framework with TypeScript, implementing modular architecture with dependency injection and decorator-based controllers.`
    ],
  },
  {
    id: 2,
    title: "Senior Frontend Developer",
    company: "BGRS",
    duration: "July 2021 - August 2023",
    location: "Toronto, ON",
    responsibilities: [
      `Revamped front-end with React.js and TypeScript, boosting load speed by 25% and user engagement by 15%.`,
      `Responsive Design and Accessibility: Implemented responsive design and accessibility features (WCAG), optimizing user experience across devices.`,
      `Integrated Google Analytics to monitor user interactions and visualize user flow across the app.`,
      `Reusable Component Library: Designed and developed a reusable component library for future use,
resulting in a 40% reduction in development time for new projects.`,
      `Unit and Integration Testing: Wrote comprehensive unit and integration tests using Jest and React Testing Library, achieving high test coverage and ensuring application reliability.`,
      `Led and contributed to technical discussions, facilitating stand-ups, sprint planning, and retrospectives.`,
    ],
  },
  {
    id: 3,
    title: "Senior Software Engineer",
    company: "Absorb Software Solutions",
    duration: "April 2020 - June 2021",
    location: "Toronto, ON",
    responsibilities: [
      `Created interactive user interfaces using HTML5, CSS3, and JavaScript`,
      `Collaborated with back-end, design, and marketing teams to ensure brand consistency and supported API integration.`,
      `Integrated SMS and payment gateways (Stripe, 3rd-party SDKs) and optimized front-end workflows with React, TypeScript, and Next.js.`,
      `Skilled in crafting GraphQL queries to fetch precise data, reducing network load and improving load times.`,
      `Used Azure Repos for version control and collaborative code management.`,
    ],
  },
  {
    id: 4,
    title: "UI Developer",
    company: "NorthStar Utilities Solutions",
    duration: "Janurary 2018 - March 2020",
    location: "Toronto, ON",
    responsibilities: [
      `Involved in various phases of Software Development Life Cycle (SDLC) of the application like Requirement gathering, Design, Analysis and Code development.`,
      `Implemented SWR (Stale-While-Revalidate) in React applications using typescript, Nodejs for efficient and performant data fetching.`,
      `Implemented web performance optimization techniques, including lazy loading, code spliting, and image optimization, to improve website speed and user experience.`,
      `Contributed to the development of responsive and mobile-first designs`,
      `Gained experience with version control systems and collaborative development.`,
    ],
  },
  {
    id: 5,
    title: "UI Developer",
    company: "HSBC",
    duration: "February 2016 - November 2017",
    location: "Toronto, ON",
    responsibilities: [
      `Involved in Requirement gathering from the client and the flow of the application as well as the application Framework.`,
      `Utilized Jira and Confluence to streamline project management and documentation, improving team productivity by 20%.`,
      `Assisted in developing user-facing features using modern JavaScript frameworks like React.js and AngularJS.`,
      `Participated in team meetings and contributed to technical discussions.`,
      `Maintained and updated existing web applications.`,
    ],
  },
];
