export const workExperienceData = [
  {
    id: 1,
    title: "Software Development Engineer",
    company: "Picton Mahoney Asset Management",
    duration: "September 2023 - Present",
    location: "Toronto, ON",
    responsibilities: [
      `Next.js Expertise: Developed and maintained a scalable front-end application using Next.js and React.js,
leveraging its server-side rendering (SSR) and static site generation (SSG) capabilities for optimal
performance and SEO.`,
      `Secured financial reporting interfaces using OAuth 2.0 and JWT with robust token handling, validation, refresh logic, and role-based access in a multi-tenant setup`,
      `Integrated OpenAI APIs into enterprise Node.js applications using TypeScript, implementing AI-powered features for financial analysis and portfolio management with robust error handling and response validation`,
      `Implemented API testing with Postman and Swagger UI, ensuring seamless integration of React/Next.js frontend with backend REST services and validating complex financial data.`,
      `Integrated RESTful APIs using Axios for secure and efficient front-end/back-end communication.`,
      `Built interactive data visualizations with Plotly.js to enable effective analysis of complex datasets.`,
      `Built enterprise-grade REST APIs using Node.js and NestJS framework with TypeScript, implementing modular architecture with dependency injection and decorator-based controllers.`,
    ],
  },
  {
    id: 2,
    title: "Senior Frontend Developer",
    company: "BGRS",
    duration: "July 2021 - August 2023",
    location: "Toronto, ON",
    responsibilities: [
      `Revamped front-end with React.js and TypeScript, boosting load speed by 25% and user engagement by 15%.`,
      `Responsive Design and Accessibility: Implemented responsive design and accessibility features (WCAG), optimizing user experience across devices.`,
      `Integrated Google Analytics to monitor user interactions and visualize user flow across the app.`,
      `Reusable Component Library: Designed and developed a reusable component library for future use,
resulting in a 40% reduction in development time for new projects.`,
      `Unit and Integration Testing: Wrote comprehensive unit and integration tests using Jest and React Testing Library, achieving high test coverage and ensuring application reliability.`,
      `Led and contributed to technical discussions, facilitating stand-ups, sprint planning, and retrospectives.`,
    ],
  },
  {
    id: 3,
    title: "Senior Software Engineer",
    company: "Absorb Software Solutions",
    duration: "April 2020 - June 2021",
    location: "Toronto, ON",
    responsibilities: [
      `Developed scalable and intuitive user interfaces for Absorb LMS, leveraging React.js, TypeScript, and Next.js to deliver fast, responsive learning experiences for enterprise clients.`,
      `Contributed to all phases of the Agile development lifecycle, including sprint planning, story estimation, daily stand-ups, and retrospectives in a Scrum/Kanban hybrid workflow.`,
      `3rd Party Integrations: Integrated SMS Gateway, Payment Gateway using Stripe and 3rd party SDK.`,
      `Supported AWS-based deployments by collaborating with DevOps teams and adapting front-end applications for cloud-native hosting environments (e.g., optimizing assets for S3 + CloudFront).`,
      `Led efforts to analyze component performance, using tools like React Profiler and Chrome DevTools to identify bottlenecks and improve overall load times and responsiveness`,
      `Integrated Jenkins into the CI/CD pipeline to automate testing and deployment of React/Next.js applications, reducing manual release efforts by 40%.`,
      `Built and deployed containerized front-end applications using Docker, ensuring reproducible environments and seamless scalability`,
    ],
  },
  {
    id: 4,
    title: "UI Developer",
    company: "NorthStar Utilities Solutions",
    duration: "Janurary 2018 - March 2020",
    location: "Toronto, ON",
    responsibilities: [
      `SDLC Involvement: Involved in various phases of Software Development Life Cycle (SDLC) of the application like Requirement gathering, Design, Analysis and Code development.`,
      `Built and enhanced interactive user interfaces for utility billing and customer service applications using JavaScript, HTML5, and CSS3, contributing to reliable experiences for utility company clients.`,
      `Helped modernize legacy UIs by refactoring outdated front-end codebases and implementing modular, component-based structures to improve maintainability and user experience.`,
      `Utilized SWR (Stale-While-Revalidate) for efficient data fetching strategies, reducing API latency and enhancing real-time interactions for customer service representatives.`,
      `Maintained a user-centric approach while updating front-end logic to accommodate frequent client-driven enhancements in NorthStar's core platform.`,
    ],
  },
  {
    id: 5,
    title: "UI Developer",
    company: "HSBC",
    duration: "February 2016 - November 2017",
    location: "Hyd, IND",
    responsibilities: [
      `Participated in Agile development processes including daily stand-ups, sprint planning, and retrospectives to support iterative development and fast delivery.`,
      `Developed and maintained responsive user interfaces using React.js, JavaScript (ES6), HTML5, and CSS3 to support internal banking applications.`,
      `Applied basic debugging and troubleshooting techniques to identify and resolve front-end bugs and performance issues.`,
      `Ensured cross-browser compatibility and responsive behavior for different screen sizes and platforms.`,
      `Project Management Tools: Utilized Jira and Confluence to streamline project management and documentation, improving team productivity by 20%.`,
    ],
  },
];
